book entity added, service and repository implemented
TetianaDenchyk/online-bookshop pull request #1
Opened 2023-10-15 12:01 UTC by TetianaDenchyk

2023-10-15 17:18 UTC, pastcwdt approved these changes
Good solution!

2023-10-16 10:22 UTC, liliia-ponomarenko requested changes
Good! Let’s  fix a few mistakes ;)

2023-10-16 10:22 UTC, liliia-ponomarenko commented on src/main/java/com/bookshop/exception/BookNotFoundException.java
> +public class BookNotFoundException extends RuntimeException {
Don’t customize your Exceptions in this case you need to create exceptions for each entity.
```suggestion
public class EntityNotFoundException extends RuntimeException {

```

2023-10-16 10:22 UTC, liliia-ponomarenko commented on src/main/java/com/bookshop/exception/BookNotSavedException.java
> +public class BookNotSavedException extends RuntimeException {
```suggestion
public class DataProcessingException extends RuntimeException {

```

2023-10-16 10:22 UTC, liliia-ponomarenko commented on src/main/java/com/bookshop/model/Book.java
> +@Data
Lombok is a great library but be [attentive when using it with Entity](https://jpa-buddy.com/blog/lombok-and-jpa-what-may-go-wrong/) JFYI

2023-10-16 10:22 UTC, liliia-ponomarenko commented on src/main/java/com/bookshop/model/Book.java
> +
```suggestion
``` 
Redundant  empty line

2023-10-16 10:22 UTC, liliia-ponomarenko commented on src/main/java/com/bookshop/repository/impl/BookRepositoryImpl.java
> +    @Autowired
As of Spring Framework 4.3, an @Autowired annotation on such a constructor is no longer necessary if the target bean defines only one constructor to begin with. See [note here ](https://docs.spring.io/spring-framework/reference/core/beans/annotation-config/autowired.html)Let’s check it ;)

2023-10-16 10:22 UTC, liliia-ponomarenko commented on src/main/java/com/bookshop/repository/impl/BookRepositoryImpl.java
> +            return session.createQuery("FROM Book b", Book.class).getResultList();
you don’t  need to use an alias here

2023-10-16 12:40 UTC, liliia-ponomarenko approved these changes

2023-10-16 12:40 UTC, liliia-ponomarenko commented on src/main/java/com/bookshop/model/Book.java
> +
```suggestion
```

2023-10-16 12:40 UTC, liliia-ponomarenko commented on src/main/java/com/bookshop/service/impl/BookServiceImpl.java
> +    @Autowired
```suggestion
```

2023-10-16 14:54 UTC, merged