Spring boot security
TetianaDenchyk/online-bookshop pull request #6
Opened 2023-11-01 14:20 UTC by TetianaDenchyk

2023-11-02 15:17 UTC, Alexsandr-Yablunovskyi approved these changes
Great job!!
Just a little comment about file naming in the "changes" directory.

2023-11-02 15:17 UTC, Alexsandr-Yablunovskyi commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
You are creating a user table but gives id: create-books-table and tableName: "books" and file name "01-create-books-table.yaml. And in the next file "02-create-users-table.yaml" you are creating a book table but table, id and file has a name "users".
I guess it's better to coordinate the name of the file and the logic written in it

2023-11-02 16:55 UTC, TetianaDenchyk commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
Thank you for noticing that! I will fix

2023-11-03 12:05 UTC, liliia-ponomarenko requested changes
Good job! Let’s improve your solution ;)

2023-11-03 12:05 UTC, liliia-ponomarenko commented on pom.xml
> +
```suggestion
```

2023-11-03 12:05 UTC, liliia-ponomarenko commented on src/main/java/com/bookshop/annotation/FieldMatch.java
> +package com.bookshop.annotation;
It’s difficult to search that your annotations and validators are placed in different packages. better move it to the validator or make this package as subpackage of the validator

2023-11-03 12:05 UTC, liliia-ponomarenko commented on src/main/java/com/bookshop/config/SecurityConfig.java
> +
```suggestion
```

2023-11-03 12:05 UTC, liliia-ponomarenko commented on src/main/java/com/bookshop/controller/BookController.java
> +    @PreAuthorize("hasRole('USER') or hasRole('ADMIN')")
you can use hasAnyRole('USER', 'ADMIN')

2023-11-03 12:05 UTC, liliia-ponomarenko commented on src/main/java/com/bookshop/dto/user/UserRegistrationRequestDto.java
> +
```suggestion
```

2023-11-03 12:05 UTC, liliia-ponomarenko commented on src/main/java/com/bookshop/exception/CustomGlobalExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.BAD_REQUEST)
CONFLICT more appropriate

2023-11-03 12:05 UTC, liliia-ponomarenko commented on src/main/java/com/bookshop/security/CustomUserDetailsService.java
> +@Component
```suggestion
@Service 
```

2023-11-03 12:05 UTC, liliia-ponomarenko commented on src/main/java/com/bookshop/security/JwtAuthenticationFilter.java
> +    private static final String AUTHORIZATION_HEADER = "Authorization";
You can use HttpHeader.AUTHORIZATION instead

2023-11-03 12:05 UTC, liliia-ponomarenko commented on src/main/java/com/bookshop/security/JwtUtil.java
> +
```suggestion
```

2023-11-03 12:05 UTC, liliia-ponomarenko commented on src/main/java/com/bookshop/service/impl/UserServiceImpl.java
> +        if (userRepository.findByEmail(request.email()).isPresent()) {
better use existsByEmail from JPA

2023-11-03 12:05 UTC, liliia-ponomarenko commented on src/main/java/com/bookshop/validator/IsbnValidator.java
> +
```suggestion
```

2023-11-03 12:05 UTC, liliia-ponomarenko commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create-drop
Why do you change it?

2023-11-03 12:05 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> -                  name: price
Why do you change create-books-table and add columns for the user?

2023-11-03 12:05 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +                  type: varchar(255)
make sure that it does not cause SQL exception

2023-11-03 12:05 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +                    nullable: false
add one empty line to the end of the file (check other files)

2023-11-03 17:26 UTC, TetianaDenchyk commented on src/main/java/com/bookshop/service/impl/UserServiceImpl.java
> +        if (userRepository.findByEmail(request.email()).isPresent()) {
there is only existsById so I left it as it is

2023-11-04 13:49 UTC, NazarSmith228 requested changes
Good job! Let's improve your solution

2023-11-04 13:49 UTC, NazarSmith228 commented on src/main/java/com/bookshop/config/SecurityConfig.java
> +    ) throws Exception {
```suggestion
            AuthenticationConfiguration authenticationConfiguration) throws Exception {
```

2023-11-04 13:49 UTC, NazarSmith228 commented on src/main/java/com/bookshop/controller/AuthController.java
> +    @ResponseStatus(HttpStatus.OK)
just FYI

`OK` is the default response status, so you can omit it

remember about this in future :)

2023-11-04 13:49 UTC, NazarSmith228 commented on src/main/java/com/bookshop/security/AuthenticationService.java
> +        final Authentication authentication = authenticationManager.authenticate(
```suggestion
        Authentication authentication = authenticationManager.authenticate(
```

2023-11-04 13:49 UTC, NazarSmith228 commented on src/main/java/com/bookshop/security/JwtAuthenticationFilter.java
> +    ) throws ServletException, IOException {
```suggestion
            FilterChain filterChain) throws ServletException, IOException {
```

2023-11-04 13:49 UTC, NazarSmith228 commented on src/main/java/com/bookshop/security/JwtUtil.java
> +
redundant blank line

2023-11-04 13:49 UTC, NazarSmith228 commented on src/main/java/com/bookshop/security/CustomUserDetailsService.java
> +                () -> new EntityNotFoundException("There is no user with email: " + username));
so `UsernameNotFoundException` or `EntityNotFoundException` ?:)

remove the `throws`

2023-11-04 13:49 UTC, NazarSmith228 commented on src/main/java/com/bookshop/service/UserService.java
> +    UserResponseDto register(UserRegistrationRequestDto request) throws RegistrationException;
```suggestion
    UserResponseDto register(UserRegistrationRequestDto request);
```

2023-11-04 13:49 UTC, NazarSmith228 commented on src/main/java/com/bookshop/service/impl/UserServiceImpl.java
> +        if (userRepository.findByEmail(request.email()).isPresent()) {
@TetianaDenchyk no, this is wrong :)

you can declare your custom method `existsByEmail`

2023-11-04 13:49 UTC, NazarSmith228 commented on src/main/java/com/bookshop/service/impl/UserServiceImpl.java
> +            throws RegistrationException {
```suggestion
    public UserResponseDto register(UserRegistrationRequestDto request) {
```

2023-11-04 13:49 UTC, NazarSmith228 commented on src/main/java/com/bookshop/validator/annotation/Isbn.java
> +@ReportAsSingleViolation
you don't have any additional constraints - therefore you don't need these annotations

2023-11-05 16:23 UTC, NazarSmith228 approved these changes
LGTM, but pls pay attention to my remarks

2023-11-05 16:23 UTC, NazarSmith228 commented on src/main/java/com/bookshop/controller/BookController.java
> +    @PreAuthorize("hasAnyRole('USER', 'ADMIN')")
shouldn't admin user also have a role `USER`? or you design your app in a way that admin does not have same priviliges as user has?

2023-11-05 16:23 UTC, NazarSmith228 commented on src/main/java/com/bookshop/dto/user/UserLoginRequestDto.java
> +) {
```suggestion
        String password) {
```

2023-11-05 16:23 UTC, NazarSmith228 commented on src/main/java/com/bookshop/service/UserService.java
> +    UserResponseDto register(UserRegistrationRequestDto request) throws RegistrationException;
@TetianaDenchyk you haven't removed `throws` here :)

2023-11-10 07:48 UTC, merged