Add category
TetianaDenchyk/online-bookshop pull request #7
Opened 2023-11-07 16:43 UTC by TetianaDenchyk

2023-11-08 09:56 UTC, SalnikovMarkiian approved these changes
Looks good to me ) 
I approved ur solution, but pay attention to my comments!

2023-11-08 09:56 UTC, SalnikovMarkiian commented on src/main/java/com/bookshop/controller/BookController.java
>      public List<BookDto> getAll(Pageable pageable) {
u can add annotation @PageableDefault with size, soty and direction parapeters to cofigure Pageable

2023-11-08 09:56 UTC, SalnikovMarkiian commented on src/main/java/com/bookshop/controller/CategoryController.java
> +    public List<CategoryDto> getAll(Pageable pageable) {
And here u can also use @PageableDefault with params

2023-11-08 09:56 UTC, SalnikovMarkiian commented on src/main/java/com/bookshop/dto/book/CreateBookRequestDto.java
> +                                   Set<Long> categoriesIds) {
it would be more logical if you add @NotEmpty under Set<Long> categoriesIds.

2023-11-08 09:56 UTC, SalnikovMarkiian commented on src/main/java/com/bookshop/mapper/BookMapper.java
> +    default Long categoryToId(Category category) {
I still can't catch the logic of this method, I think it has the right to life. But think @AfterMapping over it, and if it's needed there

2023-11-08 09:56 UTC, SalnikovMarkiian commented on src/main/java/com/bookshop/repository/CategoryRepository.java
> +
blank line

2023-11-08 15:02 UTC, liliia-ponomarenko requested changes
Great job! Let’s fix a few mistakes;)

2023-11-08 15:02 UTC, liliia-ponomarenko commented on src/main/java/com/bookshop/model/Book.java
> +    @ManyToMany
exclude from toString

2023-11-08 15:02 UTC, liliia-ponomarenko commented on src/main/java/com/bookshop/repository/BookRepository.java
> +    @EntityGraph(attributePaths = "categories")
do you really need to get books with categories?

2023-11-08 15:02 UTC, liliia-ponomarenko commented on src/main/java/com/bookshop/service/impl/BookServiceImpl.java
> +        }
you can use stream and return Set<Category> and avoid `book.getCategories().clear();`

2023-11-08 15:02 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +
```suggestion
```

2023-11-08 15:02 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/06-create-categories-table.yaml
> +                    nullable: false
add one empty line

2023-11-08 15:02 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/07-create-books_categories-table.yaml
> +                    references: categories(id)
the same

2023-11-10 08:42 UTC, liliia-ponomarenko approved these changes
Great 😊

2023-11-10 08:42 UTC, liliia-ponomarenko commented on src/main/java/com/bookshop/service/impl/CategoryServiceImpl.java
> +    }
better move it to CategoryService

2023-11-10 10:39 UTC, merged