Add order model
TetianaDenchyk/online-bookshop pull request #9
Opened 2023-11-28 14:37 UTC by TetianaDenchyk

2023-12-01 09:14 UTC, liliia-ponomarenko requested changes
Good job! Let’s  improve your solution ;)

2023-12-01 09:14 UTC, liliia-ponomarenko commented on src/main/java/com/bookshop/model/Book.java
> +
Do you really need this field here?

2023-12-01 09:14 UTC, liliia-ponomarenko commented on src/main/java/com/bookshop/model/User.java
> +
the same

2023-12-01 09:14 UTC, liliia-ponomarenko commented on src/main/java/com/bookshop/service/impl/OrderServiceImpl.java
> +        shoppingCart.getCartItems().clear();
Let’s  divide this logic by some private methods for increasing readability

2023-12-01 09:14 UTC, liliia-ponomarenko commented on src/main/java/com/bookshop/service/impl/OrderServiceImpl.java
> +        );
I see that you check it in three  methods let’s  move it to the private method

2023-12-01 09:14 UTC, liliia-ponomarenko commented on src/main/java/com/bookshop/service/impl/OrderServiceImpl.java
> +        }
the same

2023-12-01 09:14 UTC, liliia-ponomarenko commented on src/main/java/com/bookshop/service/impl/OrderServiceImpl.java
> +    public OrderItemResponseDto findOrderItemByIdInOrder(Long orderId, Long id, Long userId) {
```suggestion
    public OrderItemResponseDto findOrderItemByIdInOrder(Long orderId, Long orderItemId, Long userId) {
```

2023-12-01 09:14 UTC, liliia-ponomarenko commented on src/main/java/com/bookshop/service/impl/OrderServiceImpl.java
> +                );
can you return only one object from DB and avoid this filtration?

2023-12-04 07:41 UTC, Elena-Bruyako approved these changes
Good job! Approve, but left two comments

2023-12-04 07:41 UTC, Elena-Bruyako commented on src/main/java/com/bookshop/repository/OrderItemRepository.java
> +public interface OrderItemRepository extends JpaRepository<OrderItem, Long> {
`@Repository`

2023-12-04 07:41 UTC, Elena-Bruyako commented on src/main/java/com/bookshop/repository/OrderRepository.java
> +public interface OrderRepository extends JpaRepository<Order, Long> {
`@Repository`

2023-12-04 07:45 UTC, merged